In [6]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.16.1'

# Constantes

### Definir Constantes

In [7]:
# Definir una constante en tensorflow 2.0
tensor_20 = tf.constant([[23,4],[32,51]])

In [8]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [9]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

### Consultar los valores de un tensor

In [12]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [13]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
numpy_tensor = np.array([[23,3],[44,5]])

In [14]:
print(numpy_tensor.shape)
print(numpy_tensor)

(2, 2)
[[23  3]
 [44  5]]


In [15]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [16]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  3],
       [44,  5]])>

# Variables

### Definir Variables

In [21]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Consultar los valores de una variable

In [22]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Cambiar un valor especifico de una variable

In [23]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [24]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operaciones con tensores

In [26]:

tensor = tf.constant([[1,2],[3,4]])

In [31]:
# Operaciones con escalares
print("Tensor: ", tensor)
print("Sumar un escalar a un tensor: ", tensor + 2)
print("Multiplicar un escalar por un tensor: ", tensor * 5)

Tensor:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Sumar un escalar a un tensor:  tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)
Multiplicar un escalar por un tensor:  tf.Tensor(
[[ 5 10]
 [15 20]], shape=(2, 2), dtype=int32)


In [33]:
# Operaciones con numpy
print("Tensor original: ", tensor)
print("Obtener el cuadrado de todos los números de un tensor: ", np.square(tensor))
print("Obtener la raiz cuadrada de los números de un tensor: ", np.sqrt(tensor))

Tensor original:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Obtener el cuadrado de todos los números de un tensor:  [[ 1  4]
 [ 9 16]]
Obtener la raiz cuadrada de los números de un tensor:  [[1.         1.41421356]
 [1.73205081 2.        ]]


In [34]:
# Producto escalar entre dos tensores
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

# Strings en TensorFlow 2.0

In [35]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

### Operaciones simplmes con strings

In [36]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [38]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Almacenar arrays de strings

In [39]:
tf_string_array = tf.constant(["TensorFlw", "Deep Learning", "AI"])

In [40]:
for str in tf_string_array:
    print(str)

tf.Tensor(b'TensorFlw', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
